image_config: &image_config

  # make sure to set your Docker Hub username & password in CircleCI,
  # either as project-specific environment variables
  # or as resources in your organization's org-global Context

  IMAGE_NAME: botx-ros-image

  IMAGE_TAG: kinetic

  # NOTE: if you're modifying this config.yml file manually
  # rather than using the included setup script,
  # make sure you also add the values of your IMAGE_NAME & IMAGE_TAG variables
  # to the `test_image` job (line 55)

  LINUX_VERSION: UBUNTU_XENIAL

version: 2
jobs:
  build:
    machine: true
    environment:
      <<: *image_config

    steps:
      - checkout

      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG .

      - run: docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG && sleep 10

      - store_artifacts:
          path: Dockerfile

  test_image:
    docker:
      - image: tianhaoz95/botx-ros-image:kinetic
        environment:
          <<: *image_config

    steps:
      - checkout

      - run:
          name: test ros installation
          command: |
            source "/opt/ros/kinetic/setup.bash"
            rosversion roscpp

      - run:
          name: test python version
          command: |
            python --version
            python3 --version
            python2 --version

      - run:
          name: test pip version
          command: |
            pip --version
            pip3 --version

      - run:
          name: test virtualenv version
          command: |
            virtualenv --version

      - store_test_results:
          path: test_results

      - store_artifacts:
          path: test_results

workflows:
  version: 2
  dockerfile_wizard:
    jobs:
      - build:
          context: org-global

      - test_image:
          context: org-global
          requires:
            - build
